<dl class="clearfix">
            	<dt><a href="[field:arcurl/]">[field:image/]</a></dt>
                <dd>
                	<div class="title"><a href="[field:arcurl/]">[field:title/]</a></div>
                    <div class="des">[field:description function='cn_substr(Html2text("@me")."...",200)'/]</div>
                    <a href="[field:arcurl/]" class="more">+查看详情</a>
                </dd>
            </dl>