<dl class="clearfix">
                	<dt><a href="[field:arcurl/]">[field:image/]</a></dt>
                    <dd>
                    	<div class="title"><a href="[field:arcurl/]">[field:title/]</a></div>
                        <div class="des">[field:description function='cn_substr(Html2text("@me")."...",130)'/]</div>
                        <div class="time">
                        	<a href="[field:arcurl/]">+SEE MORE</a>
                            [field:pubdate function="GetDateMK(@me)"/]
                        </div>
                    </dd>
                </dl>