<?php
$z[0]=Array("global","",134,161);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("channel","\r\n                <li><a href=\"[field:typeurl/]\" >[field:typename/]</a></li>\r\n                ",365,506);
$z[1][4]['row']="6";
$z[1][4]['type']="top";
$z[2]=Array("global","",647,674);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",928,955);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",1212,1239);
$z[4][4]['name']="cfg_basehost";

?>